---
title: "Daily Reflection"
author: "Dylan Eldred"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Date 4/19/2022
- Hours worked today: 2
- Current tasks: Simon replication, literature review
- Deadlines: 
    - Hard: Poster (4/28/22), Paper (5/1/22)
    - Soft: Wage, LS analysis
- Reflection: I've made really good progress on the poster. I basically have everything I need except for the results, which I'm working on now. I have the probit outputs for the Simon replication and the effect on coverage for the risky workers. Currently, I'm trying to learn how to convert probit coefficients to marginal effects. From my risk_occ regression, I did find that coverage did increase in full reform states which is what I expected. Next, I need to analyze how that might effect the wages and weekly hours worked for those workers. I uploaded the Simon replication output and the summary statistics of my sample as well. Those can be found, along with my other files, in the main page of this repo.




Date 4/7/2022
- Hours worked today: 2
- Current tasks: Simon replication, literature review
- Deadlines: 
    - Hard: Poster (4/28/22), Paper (5/1/22)
    - Soft:  Literature Review (4/5/22)
- Reflection: I went back through and recoded the different levels of reform, and finally got results similar to Simon. When I restricted the sample to my treatment group (workers in risky occupations), reform was associated with an (albeit small) increase in coverage. I'm going to continue to work on my regressions with the next step trying to estimate the change (if any) in wages for those workers.



Date 4/5/2022
- Hours worked today: 2
- Current tasks: Simon replication, literature review
- Deadlines: 
    - Hard: Poster (4/28/22), Paper (5/1/22)
    - Soft:  Literature Review (4/5/22)
- Reflection: I still wasn't getting coefficients on my interaction terms to match the Simon results. I believe this may be due to me coding the timing of the reforms incorrectly. I took table 1 from Simon (2005) and stored the timing in an Excel spreadsheet. Currently, I am in the process of importing the spreadsheet into python so that I can output Stata code that will correctly time the reforms




Date 3/31/2022
- Hours worked today: 2
- Current tasks: generate summary statistics for workers (complete), continue literature review, construct DDD model, regression
- Deadlines: 
    - Hard: Poster (4/28/22), Paper (5/1/22)
    - Soft:  Literature Review (4/5/22)
- Reflection: Today I finished calculating the summary statistics for age, income, union membership, % working in a risky occupation. When I ran my initial regression including the entire sample. I did get results similar to Simon's paper. Instead of coverage rates decreasing, they increased. For next time, I'm going to look into the interaction term variables. I need to include small group with the policy variables (rpost1, rpost2, rpost3). Then after I run the probit model, I need to calculate the marginal effects.




Date 3/29/2022
- Hours worked today: 2
- Current tasks: generate summary statistics for workers, continue literature review, construct DDD model
- Deadlines: 
    - Hard: Poster (4/28/22), Paper (5/1/22)
    - Soft: Summary statistics (3/31/2022), Literature Review (4/5/22)
- Reflection: 

